<?php
declare(strict_types=1);

?>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "startSimple":{
                        "component" : "Learning_Translation/js/ui-component",
                        "template" :"Learning_Translation/localized-template"

                    }
                }
            }
        }
    }

</script>

<div data-bind="scope: 'startSimple'"> 
   <!--ko template :getTemplate() --><!-- /ko -->
</div>

<h1>Translationsss</h1>

