<?php
declare(strict_types=1);

?>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "startSimple":{
                        "component" : "Learning_Knockoutjs/js/plain-view-model"

                    }
                }
            }
        }
    }

</script>
<!-- 
Add in console for debugging

require('uiRegistry').get('startSimple')
require('uiRegistry').get('startSimple').title
---

If we want to change the title by console we need to use observable
require('uiRegistry').get('startSimple').title()=suprise

---
obserable array
require('uiRegistry').get('startSimple').exchange_rates.push({currency:'russia',rate:'10'})
require('uiRegistry').get('startSimple').exchange_rates.pop()
 -->
<div data-bind="scope: 'startSimple'"> 
<table>
  <tr>
        <td data-bind="il8n: Currency"></td>
        <td data-bind="il8n : Rate"></td>
    </tr>
    <!-- virutal element -->
    <!-- ko foreach: exchange_rates-->

    <tr>
        <td data-bind="text : currency"></td>
        <td data-bind="text : rate"></td>
    </tr>
     <!-- /ko -->
</table>
</div>