<?php
declare(strict_types=1);

?>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "startSimple":{
                        "component" : "Learning_Knockoutjs/js/plain-view-model"

                    }
                }
            }
        }
    }

</script>
<!-- 
Add in console for debugging

require('uiRegistry').get('startSimple')
require('uiRegistry').get('startSimple').title
---

If we want to change the title by console we need to use observable
require('uiRegistry').get('startSimple').title()=suprise
 -->
<div data-bind="scope: 'startSimple'"> 
<table data-bind="foreach: exchange_rates">
    <tr>
        <td data-bind="text : currency"></td>
        <td data-bind="text : rate"></td>
    </tr>
</table>
</div>