<?php
declare(strict_types=1);

?>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "startSimple":{
                        "component" : "Learning_Knockoutjs/js/plain-view-model"

                    }
                }
            }
        }
    }

</script>
<div data-bind="scope: 'startSimple'"> 
<h2 data-bind="text : title"></h2>
</div>