<?php
declare(strict_types=1);

?>

<h2>Welcome to MageDelightssDSSSSS</h2>

<!-- 
    
<script type="text/x-magento-init">
    {
        "#target": {
            "Meetanshi_Extension/js/requirejs-example": {
                "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script> -->

<!-- script orA -->
<pre id="target" data-mage-init='{"Meetanshi_Extension/js/requirejs-example":{"base_url":"/"}}'></pre>